version: '3.9'

services:
  db:
    image: postgres:15
    container_name: my-postgres
    restart: always
    ports:
      - "5436:5436"
    environment:
      POSTGRES_USER: sanchir
      POSTGRES_PASSWORD: sanchir01
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: